// Single source of truth for activity-log type labels and colors.

export const LOG_TYPES = [
  'DocumentUploaded', 'DocumentApproved', 'DocumentRejected', 'DocumentWithdrawn', 'DocumentDeleted',
  'InternCreated', 'InternUpdated', 'MentorCreated', 'MentorUpdated', 'MentorDeleted',
  'MentorTransferInitiated', 'MentorTransferAccepted', 'MentorTransferRejected', 'MentorTransferFinalised',
  'InternTransferInitiated', 'InternTransferAccepted', 'InternTransferRejected', 'InternTransferFinalised',
  'AttendanceMarked', 'AttendanceEdited',
  'GatePassRequested', 'GatePassApproved', 'GatePassRejected',
  'IdCardRequested', 'IdCardApproved', 'IdCardRejected',
  'CertificateApplied', 'CertificateApproved', 'CertificateRejected',
  'FaceEnrollmentSubmitted', 'FaceEnrollmentApproved', 'FaceEnrollmentRejected',
  'TaskAssigned', 'TaskCompleted', 'InternShiftChanged', 'PasswordReset', 'Login', 'Logout',
  'DepartmentHeadCreated', 'DepartmentHeadUpdated', 'DepartmentHeadDeleted',
  'DepartmentCreated', 'DepartmentUpdated', 'DepartmentDeleted',
  'HolidayAdded', 'HolidayUpdated', 'HolidayDeleted',
  'ShiftCreated', 'ShiftUpdated', 'SettingsUpdated',
];

export const prettifyLogType = t => (t || '').replace(/([A-Z])/g, ' $1').trim();

export const logFallbackColor = (colors, isDark) => (isDark ? colors.primaryLight : colors.primary);

export const logTypeColors = (colors, isDark) => ({
  InternCreated: colors.success,
  MentorCreated: isDark ? colors.accentLight : colors.accent,
  MentorUpdated: isDark ? colors.accentLight : colors.accent,
  MentorDeleted: colors.error,
  AttendanceMarked: isDark ? colors.primaryLight : colors.primary,
  GatePassRequested: isDark ? colors.accentLight : colors.accent,
  GatePassApproved: colors.success,
  GatePassRejected: colors.error,
  IdCardRequested: isDark ? colors.accentLight : colors.accent,
  IdCardApproved: colors.success,
  IdCardRejected: colors.error,
  CertificateApplied: isDark ? colors.accentLight : colors.accent,
  CertificateApproved: colors.success,
  CertificateRejected: colors.error,
  TaskAssigned: colors.warning,
  TaskCompleted: colors.success,
  PasswordReset: colors.warning,
  Login: colors.textMuted,
  Logout: colors.textMuted,
  DocumentUploaded: isDark ? colors.accentLight : colors.accent,
  DocumentApproved: colors.success,
  DocumentRejected: colors.error,
  DocumentWithdrawn: colors.warning,
  DocumentDeleted: colors.error,
  DepartmentHeadCreated: isDark ? colors.accentLight : colors.accent,
  DepartmentHeadUpdated: isDark ? colors.accentLight : colors.accent,
  DepartmentHeadDeleted: colors.error,
  InternUpdated: isDark ? colors.accentLight : colors.accent,
  DepartmentCreated: isDark ? colors.accentLight : colors.accent,
  DepartmentUpdated: isDark ? colors.accentLight : colors.accent,
  DepartmentDeleted: colors.error,
  FaceEnrollmentSubmitted: isDark ? colors.accentLight : colors.accent,
  FaceEnrollmentApproved: colors.success,
  FaceEnrollmentRejected: colors.error,
  MentorTransferInitiated: isDark ? colors.accentLight : colors.accent,
  MentorTransferAccepted: colors.success,
  MentorTransferRejected: colors.error,
  MentorTransferFinalised: isDark ? colors.primaryLight : colors.primary,
  InternTransferInitiated: isDark ? colors.accentLight : colors.accent,
  InternTransferAccepted: colors.success,
  InternTransferRejected: colors.error,
  InternTransferFinalised: isDark ? colors.primaryLight : colors.primary,
  AttendanceEdited: colors.warning,
  InternShiftChanged: isDark ? colors.accentLight : colors.accent,
  HolidayAdded: isDark ? colors.accentLight : colors.accent,
  HolidayUpdated: isDark ? colors.accentLight : colors.accent,
  HolidayDeleted: colors.error,
  ShiftCreated: isDark ? colors.accentLight : colors.accent,
  ShiftUpdated: isDark ? colors.accentLight : colors.accent,
  SettingsUpdated: colors.textMuted,
});