// <auto-generated />
using System;
using InternSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909080644_AddCertificateHighlightAndReport")]
    partial class AddCertificateHighlightAndReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternSystem.Core.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetInternId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TargetInternId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("FaceConfidence")
                        .HasColumnType("float");

                    b.Property<bool>("FaceVerified")
                        .HasColumnType("bit");

                    b.Property<double?>("GpsAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnLeave")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LivenessVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("LocationVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerificationSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InternId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.AttendanceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedLeaveDays")
                        .HasColumnType("int");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("SignatureRequired")
                        .HasColumnType("bit");

                    b.Property<double>("TaskThresholdPct")
                        .HasColumnType("float");

                    b.Property<double>("ThresholdPct")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AttendanceSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedLeaveDays = 5,
                            GraceMinutes = 15,
                            SignatureRequired = false,
                            TaskThresholdPct = 80.0,
                            ThresholdPct = 80.0
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.AttendanceVerificationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<double?>("DistanceFromDepartment")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FaceConfidence")
                        .HasColumnType("float");

                    b.Property<bool>("FaceVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GpsAccuracy")
                        .HasColumnType("float");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("IssuedChallenges")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LivenessVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("LocationVerified")
                        .HasColumnType("bit");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("SessionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InternId");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceVerificationSessions");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentHeadId")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentHeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HighlightTaskId")
                        .HasColumnType("int");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("InternWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguagesUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentorProjectNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectOutcomes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechStack")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("DepartmentHeadId");

                    b.HasIndex("HighlightTaskId");

                    b.HasIndex("InternId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ERP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 24.894995000000002,
                            Longitude = 67.152181999999996,
                            Name = "ERP Section",
                            RadiusMeters = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "CYBER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 24.894427,
                            Longitude = 67.151781999999997,
                            Name = "Cyber Security",
                            RadiusMeters = 100.0
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DepartmentHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MentorId");

                    b.ToTable("DepartmentHeads");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DeviceMac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InternId");

                    b.ToTable("DeviceMacs");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DocumentUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("InternId");

                    b.ToTable("DocumentUploads");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.FaceEnrollmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InternId");

                    b.ToTable("FaceEnrollmentRecords");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.GatePass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<string>("CnicImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("GatePasses");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.IdCardRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<string>("CnicImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("IdCardRequests");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.IdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FaceApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FaceEmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FaceEnrolled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FaceEnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaceEnrollmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceRejectedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MentorId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternSerialTracker", b =>
                {
                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LastSerial")
                        .HasColumnType("int");

                    b.HasKey("Prefix");

                    b.ToTable("InternSerialTrackers");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternShiftChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InternAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromShiftId");

                    b.HasIndex("InternId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ToShiftId");

                    b.ToTable("InternShiftChangeRequests");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedByMentorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndorsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndorsedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalisedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalisedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FromMentorId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitiatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InternAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToMentorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndorsedByUserId");

                    b.HasIndex("FinalisedByUserId");

                    b.HasIndex("FromMentorId");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("InternId");

                    b.HasIndex("ToMentorId");

                    b.ToTable("InternTransferRequests");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("InternId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.MentorTransferRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalisedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalisedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("FromDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("InitiatedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("MentorNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RespondedByMentorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinalisedByAdminId");

                    b.HasIndex("FromDepartmentId");

                    b.HasIndex("InitiatedByAdminId");

                    b.HasIndex("MentorId");

                    b.HasIndex("RespondedByMentorId");

                    b.HasIndex("ToDepartmentId");

                    b.ToTable("MentorTransferRequests");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.PublicHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompanyWide")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            IsCompanyWide = true,
                            Name = "Morning",
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            IsCompanyWide = true,
                            Name = "Afternoon",
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 5, 0, 0, 0),
                            IsActive = true,
                            IsCompanyWide = true,
                            Name = "Night",
                            StartTime = new TimeSpan(0, 21, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeviceBoundAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceIdHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            MustChangePassword = false,
                            PasswordHash = "$2a$11$QUWcirQwzxuIVj6yRDMcOes0jhrT6mChI2wdPdqCPnH8eJUHiH86i",
                            Role = "Admin",
                            TokenVersion = 0,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.ActivityLog", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "TargetIntern")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("TargetInternId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("PerformedByUser");

                    b.Navigation("TargetIntern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Attendance", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Attendances")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.AttendanceVerificationSession", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Intern");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Certificate", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.DepartmentHead", "DepartmentHead")
                        .WithMany()
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.InternTask", "HighlightTask")
                        .WithMany()
                        .HasForeignKey("HighlightTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Certificates")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("DepartmentHead");

                    b.Navigation("HighlightTask");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DepartmentHead", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId");

                    b.Navigation("Department");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DeviceMac", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.DocumentUpload", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.FaceEnrollmentRecord", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("FaceEnrollmentRecords")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.GatePass", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("GatePasses")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.IdCardRequest", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany("Interns")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Mentor", "Mentor")
                        .WithMany("Interns")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithOne("Intern")
                        .HasForeignKey("InternSystem.Core.Entities.Intern", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Mentor");

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternShiftChangeRequest", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Shift", "FromShift")
                        .WithMany()
                        .HasForeignKey("FromShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Shift", "ToShift")
                        .WithMany()
                        .HasForeignKey("ToShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromShift");

                    b.Navigation("Intern");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ToShift");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTask", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "AssignedByMentor")
                        .WithMany()
                        .HasForeignKey("AssignedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Tasks")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTransferRequest", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.User", "EndorsedByUser")
                        .WithMany()
                        .HasForeignKey("EndorsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.User", "FinalisedByUser")
                        .WithMany()
                        .HasForeignKey("FinalisedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Mentor", "FromMentor")
                        .WithMany()
                        .HasForeignKey("FromMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Mentor", "ToMentor")
                        .WithMany()
                        .HasForeignKey("ToMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndorsedByUser");

                    b.Navigation("FinalisedByUser");

                    b.Navigation("FromMentor");

                    b.Navigation("InitiatedByUser");

                    b.Navigation("Intern");

                    b.Navigation("ToMentor");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.LeaveApplication", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany("Mentors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("InternSystem.Core.Entities.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.MentorTransferRequest", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.User", "FinalisedByAdmin")
                        .WithMany()
                        .HasForeignKey("FinalisedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Department", "FromDepartment")
                        .WithMany()
                        .HasForeignKey("FromDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "InitiatedByAdmin")
                        .WithMany()
                        .HasForeignKey("InitiatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "RespondedByMentor")
                        .WithMany()
                        .HasForeignKey("RespondedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Department", "ToDepartment")
                        .WithMany()
                        .HasForeignKey("ToDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinalisedByAdmin");

                    b.Navigation("FromDepartment");

                    b.Navigation("InitiatedByAdmin");

                    b.Navigation("Mentor");

                    b.Navigation("RespondedByMentor");

                    b.Navigation("ToDepartment");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Notification", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Shift", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Department", b =>
                {
                    b.Navigation("Interns");

                    b.Navigation("Mentors");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Attendances");

                    b.Navigation("Certificates");

                    b.Navigation("FaceEnrollmentRecords");

                    b.Navigation("GatePasses");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.Navigation("Interns");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.User", b =>
                {
                    b.Navigation("Intern");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
